[project]
name = "fhswf-web-mining-bundestags-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scrapy>=2.11.0",
    "neo4j>=5.0.0",
    "pyyaml>=6.0.2",
    "ipykernel>=6.30.0",
]
