services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/a2v10X#sda*2!nrqw2
    volumes:
      - ./data:/data
    
